package com.cnam.magasinenligne.api

const val BASE_URL_1 = "http://localhost:8088" // clients
const val BASE_URL_2 = "http://localhost:8089" // vendeurs
const val BASE_URL_3 = "http://localhost:8090" // products
const val BASE_URL_4 = "http://localhost:8091" // order
const val BASE_URL_5 = "http://localhost:8092" // delivery
const val FULL_NAME = "fullName"
const val PHONE_NUMBER = "phoneNumber"
const val PASSWORD = "password"
const val ADDRESS = "address"
const val ID = "id"
const val EMAIL = "email"
const val CLIENT_ID = "clientId"
const val MERCHANT_ID = "merchantId"
const val PAGE_INDEX = "pageIndex"
const val NAME = "name"
const val CATEGORY = "category"
const val AGE_CATEGORY = "ageCategory"
const val SEX = "sex"
const val PRICE = "price"
const val PROVIDED_BY = "providedBy"
const val SALE_PRICE = "salePrice"
const val ON_SALE = "onSale"
const val WISH_ID = "wishId"
const val DESCRIPTION = "description"
const val TIME = "time"
const val COST = "cost"
const val FROM_CLIENT = "fromClient"
const val TO_VENDEUR = "toVendeur"
const val RECEIVERS = "receivers"
const val BROADCAST_MESSAGE = "broadcastMessage"
const val ALL_USERS = "allUsers"
const val WISHES = "wishes"
